# -*-mode:toml-*- vim:ft=toml

# ~/.config/starship.toml
# =============================================================================
# Starship cross-shell prompt configuration file.
#
# See https://starship.rs/

[battery]
full_symbol = "🔌"              # The symbol shown when the battery is full.
charging_symbol = "⚡"           # The symbol shown when the battery is charging.
discharging_symbol = "🔋"       # The symbol shown when the battery is discharging.

[[battery.display]]
threshold = 30                  # The upper bound for the display option.
style = "bold yellow"           # The style used if the display option is in use.

[[battery.display]]
threshold = 10                  # The upper bound for the display option.
style = "bold red"              # The style used if the display option is in use.

[character]
use_symbol_for_status = true    # Indicate error status by changing the symbol.

[git_state]
cherry_pick = "🍒 PICKING"      # The text shown when a cherry-pick is in progress.

[python]
pyenv_version_name = true       # Use pyenv to get Python version.
